name: Run Tests from Private Repo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      # Checkout public repo
      - name: Checkout public repo
        uses: actions/checkout@v3

      # Clone private repo 'a' using GitHub PAT
      - name: Clone private repo
        run: git clone https://$GH_TOKEN@github.com/$USERNAME/test-private.git
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          USERNAME: ${{ secrets.USERNAME }}

      # Set up Node.js (or other environment as needed)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      # Install dependencies and run tests from private repo
      - name: Install dependencies
        run: |
          cd test-private
          npm install
      - name: Run tests
        run: |
          cd test-private
          mkdir -p test-results # Ensure test-results directory is created
          npm run test 2>&1 | tee test-results/test-output.txt
        continue-on-error: true # Allows you to log results even if tests fail

      # Upload test results to AWS S3
      - name: Upload results to S3
        if: always() # This ensures results are uploaded even if tests fail
        run: |
          aws s3 cp ./test-private/test-results/ s3://$BUCKET_NAME/test-results/ --recursive
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-south-1
          BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
